name: Build and Deploy Blog

on:
  # 当 source 分支有代码推送时，自动触发
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    # 运行环境使用最新的 ubuntu
    runs-on: ubuntu-latest

    steps:
      # 第一步：拉取你的源码
      # 我们需要拉取 source 分支，因为那里是我们的写作区
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: source

      # 第二步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用一个较新的 Node.js 版本
          cache: 'npm'

      # 第三步：安装所有依赖
      - name: Install Dependencies
        run: npm install

      # 第四步：生成静态网站文件
      - name: Build Static Files
        run: npx hexo generate

      # 第五步：将生成的文件部署到 main 分支
      - name: Deploy to master branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master # 部署到 master 分支
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'